### ISSUE TITLE
when is the update coming

### ISSUE THREAD

**Issue by Yousef8760** [GregoryWullimann/FUTBoost#3]
when is the update coming and is there any solution to fix the empty cards error until the update is out ?

**Comment by GregoryWullimann** [comment]
Hi

Version 1.0.1 is already live.

Which empty cards error are you talking about?

**Comment by Yousef8760** [comment]
These bronze cards with 0 rating when you try puting fut birthday or shapeshifter or future star

**Comment by Yousef8760** [comment]
But the issue is still there

**Comment by Yousef8760** [comment]
[
![Snap 2020-04-24 at 21 24 48](https://user-images.githubusercontent.com/64249121/80244931-79700680-8672-11ea-8a47-7fd6e0d1aff2.png)

**Comment by GregoryWullimann** [comment]
> These bronze cards with 0 rating when you try puting fut birthday or shapeshifter or future star

It is working as intended.

When using those extra filters the normal results are simply filtered out. There is not a way to search directly for FUT Birthday cards or other.

 So normally searching without any filter you would have mostly gold players at low prices, so if you filter by FUT Birthday for example, you would get no results, try going through the pages and you will find one.

When using the new filters at least put in the normal filter:
1) Special card, so you don't get gold cards
2) A minimum price, like 20'000, so again you get less unwanted results.
